import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner"

import { JotaiProvider } from "@/contexts/jotai-contexts";
import { getCourses} from "@/actions/courses/getCourses";
import { getNCs } from "@/actions/ncs/getNCs";
import { getUnits } from "@/actions/units/getUnits";
import { getLearningObjectives } from "@/actions/learning_objectives/getLearningObjectives";

import { inter, merriweather, geistSans, geistMono } from '@/fonts';
import "./globals.css";
import { getLessons } from "@/actions/lessons/getLessons";
import { getCriteria } from "@/actions/criteria/getCriteria";
import { getLOLessonsMaps } from "@/actions/learning-objectives-lessons-map/getLOLessonsMap";



export const metadata: Metadata = {
  title: "Course Planner",
  description: "Generated by mr-salih.org",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {


    const {data: courses, error: coursesError} = await getCourses();
    const {data: NCs, error: NCsError} = await getNCs();
    const {data: units, error: unitsError} = await getUnits();
    const {data: los, error: loError} = await getLearningObjectives();
    const {data: lessons, error: lessonsError} = await getLessons();
    const {data: criteria, error: criteriaError} = await getCriteria();
    const {data: loLesonsMaps, error: loLessonsMapError} = await getLOLessonsMaps();

    console.log("Courses (layout): ", courses);

  return (
    <html lang="en" className="">
      <body
        className={`

          font-sans bg-background text-foreground
          ${geistSans.variable} ${geistMono.variable} ${inter.variable} ${merriweather.variable} antialiased `}
      >

    <JotaiProvider 
      initialCourses={courses} 
      initialNCs={NCs} 
      initialUnits={units} 
      initialLOs={los}
      initialLessons={lessons}
      initialCriteria={criteria}
      initialLOLessonMaps={loLesonsMaps}
      >
        <div className="flex flex-col h-screen overflow-hidden">
          <div className="p-4 flex items-center justify-between fixed top-0 left-0 right-0 z-50 bg-slate-100">
            <div>Planner</div>
            <div>Sign In</div>
          </div>

          {/* Spacer for fixed header height */}
          <div className="h-12"></div>

          <div className="flex-1 overflow-y-auto">
            {children}
          </div>
        
        </div>
    </JotaiProvider>
       
      </body>
    </html>
  );
}

export default RootLayout;
